# Generated by Django 3.2.7 on 2022-02-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0006_auto_20211115_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
