# Generated by Django 3.1.7 on 2021-10-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bmi',
        ),
    ]
